name: "Deploy staging"

concurrency:
  group: deploy-staging
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
jobs:
  build_and_deploy:
    if: ${{ github.event.repository.full_name == github.repository }}
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: "Enable yarn cache"
        uses: c-hive/gha-yarn-cache@v2  # using cache

      - name: "Setup node@16"
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: "Install dependencies"
        run: |
          yarn set version 3.1.1
          yarn install

      - name: "Deploy target: stage-mainnet"
        run: yarn run ci:build:prod
      - uses: matter-labs/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_VUE }}"
          target: stage-mainnet
          projectId: zksync-vue
          channelId: live

      - name: "Prepare /functions/"
        run: npm --prefix functions i

      - name: "Deploy functions to firebase: zksync-vue"
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_DEPLOY_TOKEN }}'